<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="Django default" uuid="1178c82f-7294-4ac2-b713-753dd00a5df0">
      <driver-ref>mysql</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/lostfound/settings.py</remarks>
      <jdbc-driver>com.mysql.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql://127.0.0.1:3306/lostfound</jdbc-url>
      <driver-properties>
        <property name="autoReconnect" value="true" />
        <property name="yearIsDateType" value="false" />
        <property name="characterEncoding" value="utf8" />
        <property name="zeroDateTimeBehavior" value="convertToNull" />
        <property name="characterSetResults" value="utf8" />
        <property name="tinyInt1isBit" value="false" />
      </driver-properties>
    </data-source>
    <data-source source="LOCAL" name="mydb" uuid="2b6302dc-d492-4305-aa91-ad884aa11aeb">
      <driver-ref>sqlite.xerial</driver-ref>
      <synchronize>true</synchronize>
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:E:\Workspace\PyCharm-workspace\lostfound\mydb.db</jdbc-url>
      <driver-properties>
        <property name="enable_load_extension" value="true" />
      </driver-properties>
      <libraries>
        <library>
          <url>file://$APPLICATION_CONFIG_DIR$/jdbc-drivers/Xerial SQLiteJDBC/3.25.1/license.txt</url>
        </library>
        <library>
          <url>file://$APPLICATION_CONFIG_DIR$/jdbc-drivers/Xerial SQLiteJDBC/3.25.1/sqlite-jdbc-3.25.1.jar</url>
        </library>
      </libraries>
    </data-source>
  </component>
</project>